export const SET_REGISTER_EMAIL = "SET_REGISTER_EMAIL";
export const CHANGE_PASS_FIELD_1 = "CHANGE_PASS_FIELD_1";
export const CHANGE_PASS_FIELD_2 = "CHANGE_PASS_FIELD_2";
export const SET_PASS_ERR = "SET_PASS_ERR";
export const SET_PASSWORD = "SET_PASSWORD";

export const SET_LOGIN_EMAIL = "SET_LOGIN_EMAIL";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";

export const CHANGE_ROUTE = "CHANGE_ROUTE";
