export const SET_REGISTER_EMAIL = "SET_REGISTER_EMAIL";
export const CHANGE_PASS_FIELD_1 = "CHANGE_PASS_FIELD_1";
export const CHANGE_PASS_FIELD_2 = "CHANGE_PASS_FIELD_2";
export const SET_FORM_ERR = "SET_FORM_ERR";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_LOGIN_EMAIL = "SET_LOGIN_EMAIL";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const CHANGE_ROUTE = "CHANGE_ROUTE";
export const SET_SESSION_CREDENTIALS = "SET_SESSION_CREDENTIALS";
export const SET_COMPOSE_INPUT = "SET_COMPOSE_INPUT";
export const SET_SFW_SCORE = "SET_SFW_SCORE";
export const SET_NSFW_SCORE = "SET_NSFW_SCORE";

export const UPLOADING_PENDING = "UPLOADING_PENDING";
export const UPLOADING_SUCCESS = "UPLOADING_SUCCESS";
export const UPLOADING_FAILED = "UPLOADING_FAILED";
export const CLEAR_IMAGE_TRAY = "CLEAR_IMAGE_TRAY";
export const PUSH_POST = "PUSH_POST";

export const SET_PM_SID = "SET_PM_SID";
export const SET_PM_USERNAME = "SET_PM_USERNAME";

export const SET_CONNECTED_SOCKETS = "SET_CONNECTED_SOCKETS";
